version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=eventful
    ports:
      - "127.0.0.1:5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
